article/urls.py
from django.urls import path
from . import views


app_name = 'article'
#path函数中的反斜杠‘ / ’很重要！！！
urlpatterns = [
    path('article_list/', views.article_list, name='article_list'),
    path('article_context/<int:id>/', views.article_context, name='article_context'),
    path('article_create/', views.article_create, name='article_create'),
    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article_edit/<int:id>/', views.article_edit, name='article_edit'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
	#处理一级评论
	path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
	#处理二级评论
	path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply'),
	#评论删除
	path('comment_delete/<int:article_id>/<int:comment_id>/', views.comment_delete, name='comment_delete'),
	#修改评论
	path('comment_edit/<int:article_id>/<int:comment_id>/', views.comment_edit, name='comment_edit'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from article.views import article_list
import notifications.urls
urlpatterns = [
    # home
    path('', article_list, name='index'),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('users/', include('users.urls', namespace='users')),
    path('password_reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('liudong/', include('liudong.urls', namespace='liudong')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
#path函数中的反斜杠‘ / ’很重要！！！
#path的name参数是给url起名的
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('display/<int:id>/', views.user_display, name='display'),
    path('edit/<int:id>/', views.user_edit, name='edit'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


# Create your models here.
'''
null 是针对数据库而言，如果 null=True, 表示数据库的该字段可以为空。
blank 是针对表单的，如果 blank=True，表示你的表单填写该字段的时候可以不填
'''
# 添加文章栏目
class ArticleColumn(models.Model):
    # 栏目标题
    title = models.CharField(max_length=100, blank=True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title


class Article(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	column = models.ForeignKey(ArticleColumn, null=True, blank=True, on_delete=models.CASCADE)
	topic = models.CharField(max_length=50)
	entry = models.TextField()
	# created = models.DateTimeField(auto_now=True)此函数
	created = models.DateTimeField(default=timezone.now)
	updated = models.DateTimeField(auto_now=True)
	# 存储正整数的字段
	total = models.PositiveIntegerField(default=0)
	#增加图片字段，增加此字段可以为空
	avatar = models.ImageField(upload_to='article/%Y-%m-%d/', blank=True, null=True)
	
	class Meta:
		# ordering指定模型返回的排列顺序
		# -created指定模型以倒叙排列
		ordering = ('-created',)

	def __str__(self):
		return self.topic
	#获取文章地址,重定向到文章详情页

	def get_absolute_url(self):
		return reverse('article:article_context', args=[self.id])

	#保存时处理图片
	def save(self, *args, **kwargs):
		article = super(Article, self).save(*args, **kwargs)
		'''
		#固定图片缩放大小
		if self.avatar and not kwargs.get('update_fields'):
			image = Image.open(self.avatar)
			(x, y) = image.size
			new_x = 1000
			new_y = int(new_x * (y / x))
			resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
			resized_image.save(self.avatar.path)
		'''
		return article

article/views.py
import markdown
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Article, ArticleColumn
from comment.models import Comment
from .form import ArticleForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# 引入分页模块
from django.core.paginator import Paginator
from django.db.models import Q
from comment.forms import CommentForm


# Create your views here.

def article_list(request):
	search = request.GET.get('search')
	order = request.GET.get('order')
	# 获取模板传回的column值
	column = request.GET.get('column')
	#初始化文章总数,获取指定登录用户的文章总数，避免搜索引擎交叉互联
	#articles_all = Article.objects.filter(author=request.user)
	#此处修改：博客网站可以允许非登录用户浏览，所以此处获取的应该为数据库中所有的文章总数！
	articles_all = Article.objects.all()
	# 判断是否有搜索
	if search:
		column = ''
		if order == 'total':
			article_li = articles_all.filter(Q(topic__icontains=search)|Q(entry__icontains=search)).order_by('-total')
		else:
			article_li = articles_all.filter(Q(topic__icontains=search)|Q(entry__icontains=search))
	elif column: 
        # Q对象中的icontains是不区分大小写的意思
        # 对于get和filter的获取值只能为id
		search = ''
		if order == 'total':
			article_li = articles_all.filter(column=column).order_by('-total')
		else:
			article_li = articles_all.filter(column=column)
	else:
        # 防止当用户没有操作时，把search=None传递给服务器
		column = ''
		search = ''
		if order == 'total':
			article_li = articles_all.order_by('-total')
		else:
			article_li = articles_all
	#实例化页码类，每六页为一页
	paginator = Paginator(article_li, 6)
	#在request中获取当前页面的页码
	page = request.GET.get('page')
	articles = paginator.get_page(page)
	context = {'articles': articles, 'order': order, 'search': search, 'column': column}
	return render(request, 'article/list.html', context)



def article_context(request, id):
	#article = Article.objects.get(id=id)  修改为错误404
	article = get_object_or_404(Article, id=id)
	comments = Comment.objects.filter(article=id)
	md = markdown.Markdown(
		extensions=[# 包含缩写、表格等扩展功能
		'markdown.extensions.extra',
		# 语法高亮
		'markdown.extensions.codehilite',
		#目录
		'markdown.extensions.toc',
		]
		)
	#将markdown语法的正文转换成html语法
	article.entry = md.convert(article.entry)
	article.total += 1
	article.save(update_fields=['total'])
	comment_count = comments.count
	comment_form = CommentForm()
	context = {
		'article': article, 
		'comments': comments, 
		'comment_form': comment_form, 
		'toc': md.toc,
		'comment_count': comment_count,
		}
	return render(request, 'article/context.html', context)


@login_required
def article_create(request):
    if request.method != 'POST':
        form = ArticleForm()
        columns = ArticleColumn.objects.all()
    else:
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            # 增加文章栏目的表单处理
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            return redirect('article:article_list')

    context = {'form': form, 'columns': columns }
    return render(request, 'article/create.html', context)


@login_required
def article_delete(request, id):
    article = get_object_or_404(Article, id=id)
    article.delete()
    return redirect('article:article_list')

@login_required
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = get_object_or_404(Article, id=id)
        if request.user != article.author:
            return HttpResponse("抱歉，你无权修改这篇文章。")
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")

@login_required
def article_edit(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method != 'POST':
        form = ArticleForm(instance=article)
        columns = ArticleColumn.objects.all()
    else:
        form = ArticleForm(data=request.POST, instance=article)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            # 增加文章栏目的表单处理
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            return redirect('article:article_context', id=id)
    context = {'form': form, 'article': article, 'columns': columns}
    return render(request, 'article/edit.html', context)

article/templates/article/context.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
 

{% block content %}
<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'prism/prism.css' %}">

<!-- 文章详情 -->
<div class="container">
	<div class="row">        
        <!-- 标题及作者 -->
		<div class="col-9">
			<h1 class="mt-4 mb-4">{{ article.topic }}</h1>
			<div class="alert alert-success">
				<div>
					{{ article.total }}阅读 — {{ comment_count }}评论 — {{ article.created|date:'Y/m/d' }} 发布
					<a href="#Comment_win" >前往评论</a>
					{% if user.is_superuser %}
						<a href="{% url 'article:article_edit' article.id %}" >编辑本文</a>·
						<a href="#" onclick="confirm_safe_delete()">删除本文</a>
						<form
						style="display:none;"
						id="safe_delete"
						action="{% url 'article:article_safe_delete' article.id %}"
						method="POST">
						{% csrf_token %}
                            <button type="submit">发送</button>
						</form>
					{% endif %}
					
				</div>
			</div>
			<br>
			<br>
			<!-- 文章正文 -->
			<div class="col-12">
            <p>{{ article.entry|safe }}</p>
		</div>
		</div>
		<!-- 新增目录 -->
		<div class="col-3 mt-4">
				<h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
		</div>
	
	</div>

    <!-- 发表评论-->
    <br>
    <br>
    <br>
    <br>
    <br>
  
    <hr>
     {% if user.is_authenticated %}
     <!-- 设置前往评论的锚点 -->
        <div id="Comment_win">
            <form action="{% url 'comment:post_comment' article.id %}" method="POST">
            {% csrf_token %}
                <!-- 评论区-->
                <div class="form-group">
                    <label for="body"><strong>我也要发言</strong></label>
                    <!-- 文本区域 -->
                    <!-- <textarea type="text" class="form-control" id="body" name="body" rows="2" ></textarea>-->
                    <div>
                        {{ comment_form.media }}
                        {{ comment_form.body }}
                    </div>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary ">发送</button>
            </form>
        </div>
    {% else %}
        <br>
        <h5 class="row justify-content-center">
            请<a href="{% url 'account_login' %}">登录</a>后回复
        </h5>
        <br>
    {% endif %}
     <!-- 显示评论 -->
    {% load mptt_tags %}
    <br>
    <h4>共有{{ comments.count }}条评论</h4>
   
<div class="row" >
		<!-- 遍历树-->
        {% recursetree comments %}
        <!-- 重命名node-->
        {% with comment=node%}
         <div class="{% if comment.reply_to %}
                        offset-1 col-11
                        {% else %}
                        col-12
                        {% endif %}" id="comment_elem_{{ comment.id }}">
                <hr>
                <p>
                    <strong style="color: pink">
                        {{ comment.user }}
                    </strong> 

                    {% if comment.reply_to %}
                        <i class="far fa-arrow-alt-circle-right" 
                           style="color: cornflowerblue;"
                        ></i>
                        <strong style="color: pink">
                            {{ comment.reply_to }}
                        </strong> 
                    {% endif %}

                </p>
                <div>{{ comment.body|safe }}</div>
                   

                <div>
                    <span style="color: gray">
                        {{ comment.created|date:"Y-m-d H:i" }}
                    </span>

                    <!-- 加载 modal 的按钮 -->
                    {% if user.is_authenticated %}
                    <button type="button" 
                            class="btn btn-light btn-sm text-muted" 
                            onclick="load_modal({{ article.id }}, {{ comment.id }})"
                            >
                        回复
                    </button>
						{% if user == comment.user %}
							<a href="{% url 'comment:comment_delete' article.id comment.id %}" >删除本条评论·</a>
							<a href="{% url 'comment:comment_edit' article.id comment.id %}" >修改本条评论</a>  
						{% endif %}
                    {% else %}
                    <a class="btn btn-light btn-sm text-muted" 
                       href="{% url 'account_login' %}">
                        回复
                    </a>
                    {% endif %}
                </div>

                <!-- Modal -->
                <div class="modal fade" 
                     id="comment_{{ comment.id }}" 
                     tabindex="-1" 
                     role="dialog" 
                     aria-labelledby="CommentModalCenter" 
                     aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                        <div class="modal-content" style="height: 480px">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                            </div>
                            <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                        </div>

                    </div>
                </div>

                {% if not comment.is_leaf_node %}
                    <div class="children">
                        {{ children }}
                    </div>
                {% endif %}
            </div>

         
         {% endwith %} 
         {% endrecursetree %} 
	</div>
</div>

<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "article:article_delete" article.id %}'
            },
        })
    }

    function confirm_safe_delete() {
        layer.open({
            title: "确认删除",
            content: "确认删除这篇文章吗？",
            yes: function(index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            }
        })
    }

<!-- 唤醒二级回复的 modal -->

    // 加载 modal
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        // 加载编辑器
        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="/comment/post-comment/' + 
                article_id + 
                '/' + 
                comment_id + 
                '"' + 
                ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' + 
                comment_id + 
                '"></iframe>';
            $(modal_body).append(content);
        };

        $(modal_id).modal('show');
    }



<!-- 找到页面中class='django-ckeditor-widget'的容器，然后删除这个容器的style属性。-->
    <!--以此来解决富文本编辑器宽度无法自适应问题 -->

    $(".django-ckeditor-widget").removeAttr('style');


// 新增函数，处理二级回复
    function post_reply_and_show_it(new_comment_id) {
        let next_url = "{% url 'article:article_context' article.id %}";
        // 去除 url 尾部 '/' 符号
        next_url = next_url.charAt(next_url.length - 1) == '/' ? next_url.slice(0, -1) : next_url;
        // 刷新并定位到锚点
        window.location.replace(next_url + "#comment_elem_" + new_comment_id.toString());
    };
</script>

{% endblock content %}

article/templates/article/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} 写文章 {% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="topic">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="topic" name="topic" required>
                </div>
                 
                 <div class="form-group">
                    <label for="entry">文章正文</label>
                    <!-- 文本区域 -->
                 <textarea type="text" class="form-control" id="entry" name="entry" rows="12" required></textarea>

                 </div>

                <div class="form-group">
                     <!-- 标签 -->
                    <label for="column">栏目</label>
                    <!-- 选择框 -->
                    <select class="form-control" id="column" name="column">
                        <option value="none">请选择栏目</option>
                        {% for column in columns %}
                          <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>
				<!--文章标题图-->
				<div class="form-group">
			<label for="avatar">标题图</label>
			<input type="file" class="form-control-file" name="avatar" id="avatar">
			</div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

article/templates/article/edit.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} 编辑文章 {% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form action="." method="post">
                {% csrf_token %}
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="topic">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="topic" name="topic" value="{{ article.topic }}">
                </div>

                <div class="form-group">
                    <label for="entry">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="entry" name="entry" rows="12">{{ article.entry }}</textarea>
                </div>

                <div class="form-group">
                     <!-- 标签 -->
                    <label for="column">栏目</label>
                    <!-- 选择框 -->
                    <select class="form-control" id="column" name="column">
                        <option value="none">请选择栏目</option>
                        {% for column in columns %}
                          <option value="{{ column.id }}"
                          {% if column.id == article.column.id %}
                                selected
                          {% endif %}
                          >{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

article/templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load my_filter %}

<!-- 写入 base.html 中定义的 title -->


<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?search={{ search }}&colunm={{ column }}">
                    最新
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=total&search={{ search }}&column={{ column }}">
                最热
                </a>
            </li>
        </ol>

    </nav>

    <!-- 新增，搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text"
                    class="form-control mb-2 mr-sm-2"
                    name="search"
                    placeholder="搜索文章..."
                    required>
            </form>
        </div>
    </div>
    <!-- 搜索提示语 -->
     {% if search %}
        {% if articles %}
     <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>

        {% else %}
      
        <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
            <hr>
        {% endif %}
    {% endif %}


		<!-- 列表循环 -->
    <div class="row mt-2">
	
    {% for article in articles %}
        <!-- 文章内容 -->

             <!-- 标题图 -->
       <div class="col-3">
        {% if article.avatar %}
          
                <img src="{{ article.avatar.url }}" 
                     alt="avatar" 
                     style="border-radius: 20px"
                     class="img-fluid"
                     >
          
        {% endif %}
        </div>
      
        <div class="col-9">
            <!-- 栏目 -->
            {% if article.column %}
                <a href="{% url 'article:article_list' %}?column={{ article.column.id }}">
                    <button type="button"
                    class="btn btn-sm mb-2
                        {% if article.column.title == 'Django' %}
                            btn-success
                        {% elif article.column.title == 'Python' %}
                            btn-danger
                        {% elif article.column.title == 'HTML' %}
                            btn-warning
                        {% endif %}
                    "
                >
                    {{ article.column }}
                </button>
                </a>
            {% endif %}
            <!-- 标题 -->
            <h4>
                <b>
                    <a href="{% url 'article:article_context' article.id %}"style="color: black;">
                        {{ article.topic }}
                    </a>
                </b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    {{ article.entry|slice:'100' |safe}}...
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 附加信息 -->
                <span>
					<i class="fas fa-eye" style="color: lightskyblue;"></i>
                    <span style="color: colorful">{{ article.total|trans_watched }} &nbsp;&nbsp;&nbsp;</span>
                </span>

					
                <span>
					<i class="fas fa-clock" style="color: pink;"></i>
                    {{ article.created|trans_time }} 
                </span>
            </p>

      

        </div>
  <br>
		 <hr style="width: 100%;"/>
	{% endfor %}
     
    </div>	

	


        <!-- 页码导航 -->
    <div class="pagination row ">
        <div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
                <a href="?page=1&order={{order}}&search={{ search }}&column={{ column }}" class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}&order={{order}}&search={{ search }}&column={{ column }}"
                   class="btn btn-secondary"
                >
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

            <!-- 当前页面 -->
          
            
            <span class="current btn btn-danger btn-lg">
                {{ articles.number }}
            </span>
			
            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}&order={{order}}&search={{ search }}&column={{ column }}"
                   class="btn btn-secondary"
                >
                    {{ articles.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ articles.paginator.num_pages }}&order={{order}}&search={{ search }}&column={{ column }}"
                   class="btn btn-success"
                >
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
    </div>
</div>

	
</div>

{% endblock content %}