article/urls.py
from django.urls import path
from . import views


app_name = 'article'
#path函数中的反斜杠‘ / ’很重要！！！
urlpatterns = [
    path('article_list/', views.article_list, name='article_list'),
    path('article_context/<int:id>/', views.article_context, name='article_context'),
    path('article_create/', views.article_create, name='article_create'),
    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article_edit/<int:id>/', views.article_edit, name='article_edit'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from article.views import article_list
import notifications.urls
urlpatterns = [
    # home
    path('', article_list, name='index'),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('users/', include('users.urls', namespace='users')),
    path('password_reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('liudong/', include('liudong.urls', namespace='liudong')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice' 

urlpatterns = [
	#通知列表
	path('list/', views.Comnotview.as_view(), name='list'),
	#更新通知列表
	path('update/', views.Comnotupdateview.as_view(), name='update'),

]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
#path函数中的反斜杠‘ / ’很重要！！！
#path的name参数是给url起名的
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('display/<int:id>/', views.user_display, name='display'),
    path('edit/<int:id>/', views.user_edit, name='edit'),
]

templates/back_top.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>
<script>
	$(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>
<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 50%;
        opacity: 0.7;
        background: white;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 8px;
        border-radius: 3px;
        background: black;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
<!-- 载入静态文件 -->

{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
   <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>{% block title %}首页{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" 
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" 
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" 
      crossorigin="anonymous"
    >
   
    
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <div class="content">
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    </div>
    <footer class="footer">
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
	</footer>
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->

    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>    
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
     <!-- 引入layer.js -->
    <script src="{% static 'layer/layer.js' %}"></script>
    <!-- 载入VUE
	<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script> -->

    <!--  引入上浮按钮文件-->
    {% include 'back_top.html' %}
<!--增加样式-->
	<style>
	html, body {
		height: 100%;
	}
	body {
		display: flex;
		flex-direction: column;
	}
	.content {
		flex: 1 0 auto;
	}
	.footer {
		flex-shrink: 0;
	}
	</style>
</body>

</html>

templates/base6.html
<!-- 载入静态文件 -->

{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
   <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>{% block title %}绿地•临沂城际空间站{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" 
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" 
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" 
      crossorigin="anonymous"
    >
   
    
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header6.html' %}
    <div class="content">
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    </div>
    <footer class="footer">
    <!-- 引入注脚 -->
    {% include 'footer6.html' %}
	</footer>
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->

    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>    
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
     <!-- 引入layer.js -->
    <script src="{% static 'layer/layer.js' %}"></script>
    <!-- 载入VUE
	<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script> -->

    <!--  引入上浮按钮文件-->
    {% include 'back_top.html' %}
<!--增加样式-->
	<style>
	html, body {
		height: 100%;
	}
	body {
		display: flex;
		flex-direction: column;
	}
	.content {
		flex: 1 0 auto;
	}
	.footer {
		flex-shrink: 0;
	}
	.lunboimg {
  list-style-type: none;
}
.lbimg {
  position: absolute;
}
.lunbobtn {
  position: absolute;
  top: 75%;
  left: 40%
}
.lbbtn {
  margin-left: 10px;
  display: inline-block;
  background-color: gray;
  border-radius: 50%;
  width: 20px;
  height: 20px;
}
.lbbtn:hover {
  width: 22px;
  height: 22px;
}
.rtriangle{
  margin-top: 50px;
  width: 0;
  height: 0;
  border-width:70px 40px;
  border-style: solid;
}
.righttriangle {
  position: absolute;
  top: 40%;
  left:78%;
  display: inline-block;
  border-right: 10px solid; border-bottom: 10px solid;
  width: 50px; height: 50px;
  transform: rotate(-45deg);
}
.righttriangle:hover {
  border-right: 12px solid yellow; border-bottom: 12px solid yellow;
}
.lefttriangle {
  position: absolute;
  top: 40%;
  left:17%;
  display: inline-block;
  border-left: 10px solid; border-bottom: 10px solid;
  width: 50px; height: 50px;
  transform: rotate(45deg);
}
.lefttriangle:hover {
  border-left: 12px solid yellow; border-bottom: 12px solid yellow;
}
	</style>
</body>

</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark" >
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 别瞅了，见底了！！</p>
    </div>
</footer>

templates/footer6.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark" >
    <div class="container">
        <p class="m-0 text-center text-white">绿地•临沂城际空间站
</p>
    </div>
</footer>

templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}

{% block title %}
	
{% endblock %}

<link rel="stylesheet" href="alert.css">
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="{% url 'article:article_list' %}">我的博客</a>

    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
        <!-- 条目 -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
        </li>

        {% if user.is_authenticated %}
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <!-- 如果有消息通知就在用户名之前加上小红点 -->
			{% if unread_count %}
            <svg viewBox="0 0 8 8"
                 width="8px"
                 height="8px">
                <circle cx="4"
                        cy="4"
                        r="4"
                        fill="#ff6b6b"
                        ></circle>
            </svg>
        {% endif %}
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'notice:list' %}">通知
              {% if unread_count %}
              <span class="badge badge-danger">{{ unread_count }}</span>
              {% endif %}
              </a>
                {% if user.is_superuser %}
              <a class="dropdown-item" href="{% url 'article:article_create' %}">写文章</a>
               {% endif %}
              <a class="dropdown-item" href="{% url 'users:logout' %}">退出登录</a>
              <a class="dropdown-item" href="#" onclick="user_delete()">删除用户信息</a>
              <a class="dropdown-item" href="{% url 'users:display' user.id %}">个人信息</a>
              <a class="dropdown-item" href="{% url 'users:edit' user.id %}">个人信息修改</a>
            </div>
        </li>
         {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">登录</a>
        </li>
        {% endif %}


        {% if user.is_authenticated %}
        <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function(index, layero) {
                    location.href="{% url 'users:delete' user.id %}"
                },
            })
        }
        </script>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>

templates/header6.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}

{% block title %}
	
{% endblock %}

<link rel="stylesheet" href="alert.css">
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="#">绿地•临沂城际空间站
</a>

   
  </div>
</nav>